### ISSUE TITLE
Feature Request [autoPlay, addNext]

### ISSUE THREAD

**Issue by L0SER8228** [AkaruiDevelopment/aoi.js#205]
It'll be great if you add this feature
### Music Related
`Autoplay`: when enabled, the bot wil continue playing after there is no more songs in the queue.

`playNext` / `addNext` : Add the next song right after the current playing song in the queue, so we can play it next
`playSkip` : combination of `playNext` and `skip`, skip the current song and play the requested song instantly without affecting the existing queue.

#### Comannd Handler
add `cooldown`, `guildOnly`, `ownerOnly`, `botPermissions`, ` userPermissions` to comamnd handler.
 I know all functions are available. But we have to write every function and their error message for every commands. Isn't `aoijs` to simplify and make easy discord bot developing, so make it easy.
 Bot owner id can be array , and can be added while making `new aoi.Bot`

If `guildOnly`function will added to Comamnd handler, we can decide for every comamnd to be used on dm or not.
`ownerOnly`: A new event should be added which will be emitted when a non owner user try to use the command.

To add `cooldown` to command handler, a new event should be made, it'll be emitted when there is still a cooldown 

`botPermissions`: it should be array . And a new event should be added, it'll emit when the bot don't have permission for that comand

`userPermissions`: it should be array . And a new event should be added, it'll emit when the user don't have permission to use that comand

**Comment by BeastBoyADI** [comment]
I liked the guildOnly stuff in cmd handler for letting the bot to respond to dms for only some cmds. Also the music related cmds should be added. I will like to see this in the next update. Pls leref do it as it's a cool feature

**Comment by USERSATOSHI** [comment]
> I liked the guildOnly stuff in cmd handler for letting the bot to respond to dms for only some cmds. Also the music related cmds should be added. I will like to see this in the next update. Pls leref do it as it's a cool feature

about that, I working in on it 
but because AOIJS src code needs a update so it will take quite a time

**Comment by L0SER8228** [comment]
Further a default `help` comamnd can be added.

**Comment by USERSATOSHI** [comment]
> Further a default `help` comamnd can be added. 

why help?

**Comment by L0SER8228** [comment]
> > Further a default `help` comamnd can be added.
> 
> why help?

Not necessary, still it'll be a good feature

**Comment by USERSATOSHI** [comment]
> Further a default `help` comamnd can be added. 

so what does `help` actually do?

**Comment by Leref** [comment]
The point of aoi.js is to be simplified :)
These are great ideas, yet it will be a while from now.
Aoi.JS will be updated into discord.js v13, this will include a huge rewrite.
There will be small updates but definitely great ideas for the Command Handler.
Personally Music in future should be rewritten and more compact, less heavy and more with options.
The default help command isn't really needed but I will keep in mind.

**Comment by USERSATOSHI** [comment]
> The point of aoi.js is to be simplified :)
> These are great ideas, yet it will be a while from now.
> Aoi.JS will be updated into discord.js v13, this will include a huge rewrite.
> There will be small updates but definitely great ideas for the Command Handler.
> Personally Music in future should be rewritten and more compact, less heavy and more with options.
> The default help command isn't really needed but I will keep in mind.

oh so that what's `help` meant

**Comment by USERSATOSHI** [comment]
> > > Further a default `help` comamnd can be added.
> > 
> > why help?
> 
> Not necessary, still it'll be a good feature
> discord.py has actually, from there i get the idea

you can simply do
```js $djsEval[client.bot_commands.map(x=>x.name).join(" , ");yes]
```

and this will give you all cmds name

**Comment by USERSATOSHI** [comment]
regarding this

i have some news on command handler

rn 
we have added 2 new features

`dmOnly : true/false` makes cmd only work in dm
tho
plans are to change it to `sendOnlyAt : 'dm' | 'guild' | 'both' ` 
default will be `both`

tho u still have to add `guildOnly : false` in `bot.onMessage()`

furthermore,
`whitelist: true/false` (default = false ) has been added to cmds to support new Blacklist system

cmds with `whitelist : true` will make these cmds usable for the users who are blacklisted

no idea about `ownerOnly` and music ones

also a question on `cooldown` do u want this to be temp cooldown aka it resets on restart ( doesnt use db , good for small cooldowns) or permanent cooldown aka which doesnt restart (uses db, good for long cooldowns, bad for short ones)

**Comment by Leref** [comment]
I will be closing this at the moment. 
The upcoming version of `aoi.js` will introduce several support for Music itself and various advanced options.
