### ISSUE TITLE
No database support from quick.db, code used from docs

### ISSUE THREAD

**Issue by pogboi69** [AkaruiDevelopment/aoi.js#340]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ *] Others: Database not supported for quick.db

Code used: From docs, https://aoi.leref.ga/v/aoi.js-v5/options/databaseoptions
```
database: {
        type: "custom",
        db: require('quick.db'),
        tables: ["main"],
        promisify: true
    },
```
Error received: 
```
DatabaseSupportError: Database Not Supported , You Can Create An Issue At aoi.js Github.
Link : https://github.com/aoijs/aoi.js
```

Edit:
```
The bot stores the data, but after restart, the bot sends commands twice and the first message from the bot has the stored data and the other message from the bot does not have any data stored data

example:
(command): !eval $setglobaluservar[test;true] data stored
(bot): data stored
(heroku console): node .
(command): !eval $getglobaluservar[test]
(bot): true
         false

Here first message is true which means data stored,
second message is false which means data not stored,

It is also repeated twice.


oh i'm bad at explaining
```

More:
- Aoi.js version: 5.0.7
- Node.js version: 16.13.1
- Operating system: windows
- Hosted on: Heroku

Screenshots (If any): Image or Link

**Comment by USERSATOSHI** [comment]
can u djseval client.db and send it

**Comment by seriousdev-chan** [comment]
> can u djseval client.db and send it

sure, here it is

Promisify {
  path: './database',
  tables: [Array],
  module: [Object],
  promisify: false,
  type: 'custom',
  extraOptions: {},
  methods: [Array],
  tableList: [Object]
}

**Comment by USERSATOSHI** [comment]
what if u set a number like 10 in var instead of boolean

**Comment by seriousdev-chan** [comment]
> what if u set a number like 10 in var instead of boolean

thats resets too after restart of bot

**Comment by seriousdev-chan** [comment]
> > what if u set a number like 10 in var instead of boolean
> 
> thats resets too after restart of bot basically every var resets

i also tried dbdjs.db, but dbdjd.db too didnt store any data or anything, i evaled $djseval[client.db;yes] and it showed this:

```
AoijsAPI {
  path: './database/',
  tables: [Array],
  module: [Object],
  promisify: false,
  type: 'dbdjs.db',
  db: [Database],
  extraOptions: {}
}
```

**Comment by USERSATOSHI** [comment]
huh then i think its an issue from the host side

**Comment by USERSATOSHI** [comment]
closed due to inactivity

u can open again if this persist
