### ISSUE TITLE
LavaLink song name bug

### ISSUE THREAD

**Issue by OPcaliverYT** [AkaruiDevelopment/aoi.js#345]
## Type
- [x] Functions: \<$lavalinkExecute>
- [x] Callbacks: \<bot.onMessage()>
- [x] Handlers: \<none>

Code used:
```
bot.command({
    name: "queue",
    code: `
    $title[1;Player's queue]
    $image[1;$lavalinkExecute[getthumbnail;$lavalinkExecute[songinfo;identifier];hqdefault]]
    $description[1;Now playing [$lavalinkExecute[songinfo;title]]($lavalinkExecute[songinfo;url])
$lavalinkExecute[queue]
$suppressErrors[no songs in queue]
    $color[1;RANDOM]
   `
});
```

More:
- Aoi.js version:5.0.8
- Node.js version:17.0.1
- Operating system:Android 8

![Screenshot_2022_0120_200509](https://user-images.githubusercontent.com/92639283/150359125-dfe6017b-78d3-4e1e-8ce2-bd21fa05a709.png)

**Comment by Leref** [comment]
The first assigned song will not show as its already in queue and being played, due the songInfo code itself, after any songs being in queue will show.

**Comment by LuCk-exxtreme** [comment]
Eventually It shows the recently added song as now playing too. I used trackID as 0 but still no affect
