### ISSUE TITLE
Please reevaluate making the all function of the CustomDB class in Database.js an asynchronous function

### ISSUE THREAD

**Issue by guihrib** [AkaruiDevelopment/aoi.js#349]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ X ] Others: \Please attention in Database.js Line 371

## Description
> we made the changes in aoi.fb to work in customdb, but there is one thing that prevents the all method from working. the fact that the customdb "all" is not an async function and thus, the "await" of the aoi.fb method cannot work, because for it to pull the data it needs to wait for it to arrive, thus, the "await" being used only by an async function
> 
https://github.com/AkaruiDevelopment/aoi.js/blob/main/src/classes/Database.js
![image](https://user-images.githubusercontent.com/61317250/150699991-1188b467-afb7-4e71-9e19-5e65203d1af9.png)

the only way for it to work, is to make customdb's "all" function, async. or to support ai.fb, add ai.js as another type
we made the changes you(Leref) said, but the all gives error because the customdb class doesn't have the all method as function async

changes made (the changes you(Leref) told us to make):
https://github.com/aoifb/aoi.fb/tree/v3

**Comment by USERSATOSHI** [comment]
sure
just give me some time
i will do that when i am free

**Comment by Leref** [comment]
Issue being handled in #353.
