### ISSUE TITLE
Select Menu for parsers, doesn't disable itself even making the property "true".

### ISSUE THREAD

**Issue by NeoAIChan** [AkaruiDevelopment/aoi.js#352]
## Type
- [×] Functions: \<Select Menu>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$sendMessage[{"content":"e", "components":"{actionRow:{selectMenu:h:ello:1:1:true:{selectMenuOptions:its not disabled:0:test:true}}}"}]
```

More:
- Aoi.js version: v5.1.0-dev
- Node.js version: 16+
- Operating system: 

Screenshots (If any): Image or Link

**Comment by USERSATOSHI** [comment]
added disabled property in parser
