### ISSUE TITLE
$hasPermsInChannel

### ISSUE THREAD

**Issue by xAkihiro666** [AkaruiDevelopment/aoi.js#356]
## Type
- [ ] Functions: \$hasPermsInChannel

## Description
Well, the function usage is **$hasPermsInChannel[channelID;userID;perm1;perm2;...]**... and it only allows us to get userID, so I'm hoping that you'd add a feature that'd allow us to use $guildID or $roleID in the userID line.

**Comment by USERSATOSHI** [comment]
sure

**Comment by USERSATOSHI** [comment]
added ✔️
