### ISSUE TITLE
$findChannel

### ISSUE THREAD

**Issue by xAkihiro666** [AkaruiDevelopment/aoi.js#357]
## Type
- [ ] Functions: $findChannel

## Description
So this is the current one **$findChannel[ID/mention/name;returnCurrentChannel (yes/no) (optional)]**... It doesn't give any option on whether we are finding a Channel or a Category... So I tried making a category named hello and a text channel named hello, then tried to eval this command **$findChannel[hello]**, it returned the category ID instead of the text channel ID... So I hope that you'd add an option like... **$findChannel[ID/mention/name;Text/Category/Voice;returnCurrentChannel (yes/no) (optional)]**

**Comment by NeoAIChan** [comment]
Well, currently it works like **with link** instead with name to be honest.

**Comment by xAkihiro666** [comment]
> Well, currently it works like **with ID** instead with name to be honest.

But, wouldn't it be great if they'd add something like "Text/Category/Voice"

**Comment by NeoAIChan** [comment]
> > Well, currently it works like **with ID** instead with name to be honest.
> 
> But, wouldn't it be great if they'd add something like "Text/Category/Voice"

Umm, no? 
Cause you're entering the ID already so what is the point of adding category/text/voice?
ID already defines the channel is type, name, raw position and more things. Have a nice day.

**Comment by NeoAIChan** [comment]
> Umm, no? Cause you're entering the ID already so what is the point of adding category/text/voice? ID already defines the is type, name, raw position and more things.

*I have said those things for desktop users, I do know mobile users can't get voice channel's ID.*

**Comment by Leref** [comment]
The current methods don't allow us to obtain it.
Regardless, it is not hard to find a loophole in order to achieve what you want.
