### ISSUE TITLE
Embed Errors

### ISSUE THREAD

**Issue by NeoAIChan** [AkaruiDevelopment/aoi.js#358]
## Type
- [ ] Function: embed-errors

## Description
Hello, I wanted to request about; Since we can use only description, title, fields, footer etc. as functions *(`$description` as example)*, so why we don't have kind of that feature for embed errors?

Because of that, example we can't get embed as "allEmbeds" due the embed lacking of "description".

**Comment by USERSATOSHI** [comment]
what?

**Comment by NeoAIChan** [comment]
> what?

The issue was on my code, fixed it.
