### ISSUE TITLE
Clearing/purging issue

### ISSUE THREAD

**Issue by NeoAIChan** [AkaruiDevelopment/aoi.js#359]
## Type
- [ ] Functions: `$clear`

#### Example code I used:
```js
$clear[$sum[1;$slashOption[amount];$replaceText[$interactionData[options.data[1].value];undefined;everyone]]
```

## Information:
- aoi.js version: v5.1.1-dev

Issue I want to talk about; `$clear` function still counting sent messages even we use "user" property on it.

**Example:** 
\+ Hello!
\- Hi!
\+ How are you?
\- I'm fine, thanks. You?

"+" = A user, "-" = B user

So, if we try to delete "A" user's _a message_, it won't delete it cause it will also count "B" user's message. Purging A's message will be failed. I'm considering this as bug.

**Comment by USERSATOSHI** [comment]
how did u use user property

**Comment by Neodevils** [comment]
> how did u use user property

Like I showed on example.
