### ISSUE TITLE
Bug: $ban not deleting the messages of the given timespan

### ISSUE THREAD

**Issue by Faf4a** [AkaruiDevelopment/aoi.js#460]
### Bug Type

Function

### Bugged Function

```js
$ban[guild;user;days;reason]
```
- Not deleting the messages given in the deletionDays argument (of the given time span).
- https://discord.com/channels/773352845738115102/1123918875751370905

### Version of aoi.js

v6.2.6 - v7.0.0

### Version of Node.js

v18.14.0 (LTS)

### Excepted Output

The "bot" deleting the messages of the given user of the last 7 days or so.

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
> The issue is `days` has been deprecated in discord.js, it should be replaced with the `deleteMessageSeconds` parameter.
> 
>     * https://discord.js.org/#/docs/discord.js/main/typedef/BanOptions

yes indeed it got deprecated, but that is not the issue 

issue is that property name is changed from `days` to `deleteMessageDays` 

which is why it didn't delete it

but yes it has to be changed to `deleteMessageSeconds`

**Comment by Leref** [comment]
Entirely rewrote the function to support 7 to interpret as 7 days.

Resolved in commit: https://github.com/AkaruiDevelopment/aoi.js/commit/5b98b6f8f601cddadc2314ae9ef59de979f30104
