### ISSUE TITLE
Bug: $math invalid exponentiation 

### ISSUE THREAD

**Issue by Faf4a** [AkaruiDevelopment/aoi.js#499]
### Bug Type

Function

### Bugged Function

```js
$math[3^2]


Output:
1
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v16.11.0 (Lowest)

### Excepted Output

3^2: 9

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
`^` in javascript is considered for [bitwise xor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_XOR) not for power

hence 3 ^ 2 =>  11 ^ 10 => 01 => 1
for exponentiation use [`**`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation)
